<template>
  <!--
    Unused at native runtime: nativescript-vue mounts .nuxt-native/root-frame.vue
    (generated by the `nuxt-native` CLI from app/pages) instead of Nuxt's own
    client entry. This file only exists so `nuxi dev`/`nuxi typecheck` — which
    still expect a root component — have something to resolve.
  -->
  <div />
</template>
