// Generated by `nuxt-native create`. `corePlugins` is deliberately an
// allowlist (not the full Tailwind set) — see the comment above
// TAILWIND_CORE_PLUGINS in nuxt-native's own cli/lib/scaffold-templates.mjs
// for exactly which utilities NativeScript's CSS engine can and can't
// apply, and why. Safe to edit, but removing entries here doesn't make
// NativeScript support them — it only controls what Tailwind generates.
module.exports = {
  content: ['./app/**/*.vue', './.nuxt-native/**/*.{js,vue}'],
  corePlugins: [
    "margin",
    "padding",
    "gap",
    "width",
    "height",
    "minWidth",
    "minHeight",
    "maxWidth",
    "maxHeight",
    "backgroundColor",
    "borderRadius",
    "borderWidth",
    "borderColor",
    "boxShadow",
    "opacity",
    "textColor",
    "fontSize",
    "fontWeight",
    "fontFamily",
    "fontStyle",
    "textAlign",
    "textDecoration",
    "textTransform",
    "letterSpacing",
    "lineHeight",
    "whiteSpace",
    "textOverflow",
    "visibility",
    "zIndex",
    "flexDirection",
    "flexWrap",
    "flex",
    "flexGrow",
    "flexShrink",
    "order",
    "justifyContent",
    "alignItems",
    "alignContent",
    "alignSelf"
  ],
  theme: {
    extend: {}
  }
}
