<template>
  <!-- Unused at native runtime: nativescript-vue mounts .nuxt-native/root-frame.vue
       (generated by `nuxt-native init`/`dev`/`build` from app/pages) instead of
       Nuxt's own client entry. This file only exists so `nuxi dev`/typecheck have
       a root component to resolve. -->
  <div />
</template>
